version: '3'

services:

  web:
    image: nginx:latest
    container_name: nginx_dev
    ports:
      # "Host Port:Container Port"
      - "8080:80"
    volumes:
      # コンフィグファイルをホストOSとコンテナ内で同期
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # コンテンツをホストOSとコンテナ内で同期
      - ./html:/var/www/html
      # HTTPS用の証明書とキーをホストOSとコンテナ内で同期
      #- ./???:./???
    tty: true

  db:
    image: mariadb:latest
    container_name: mariadb_dev
    ports:
      - '${FORWARD_DB_PORT}:3306'
    volumes:
      # データをホストOSとコンテナ内で同期
      - ./db/sql_data:/var/lib/mysql
      # コンフィグファイルをホストOSとコンテナ内で同期
      - ./my.cnf:/etc/mysql/my.cnf
    restart: always
    environment:
      # アカウントとDBを設定
      MYSQL_DATABASE: '{DB_DATABASE}'
      MYSQL_USER: '{DB_USER}'
      MYSQL_PASSWORD: '{DB_PASSWORD}'
      MYSQL_HOST: '{DB_HOST}'
      MYSQL_ROOT_PASSWORD: '{DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      TZ: '${TZ}'

  Adminer:
    image: Adminer
    conteiner_name: adminer_dev
    restart: always
    ports: '${FORWARD_AD_PORT}:8080'
