version: '3'

services:

  node:
    image: node:latest
    working_dir: /home/workspace
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ./node/workspace:/home/workspace
    networks:
      - br0

  web:
    image: nginx:latest
    container_name: nginx_dev
    ports:
      # "Host Port:Container Port"
      - "8080:80"
    volumes:
      # コンフィグファイルをホストOSとコンテナ内で同期
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
      # コンテンツをホストOSとコンテナ内で同期
      - ./web/html:/var/www/html
      # HTTPS用の証明書とキーをホストOSとコンテナ内で同期
      # - ./???:./???
    networks:
      - br0

networks:
  br0:
    driver: bridge
